# Generated by Django 5.2.8 on 2025-11-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('stock_symbol', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.FloatField()),
                ('purchase_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
